#Retrieve all library employees along with their contact points.

PREFIX ex: <http://example.org/library>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX emp: <http://example.org/emp#>
PREFIX nlon: <http://example.org/nlon#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?author_name ?book_name ?library_name
WHERE {
    ?author a dt:Author;
            foaf:name ?author_name.
    ?book a schema:Book;
          dcterms:title ?book_name;
          schema:creator ?author.
    ?library a schema:Library;
            foaf:name ?library_name;
            cdesc:hasInventory ?book.
}
GROUP BY ?author
HAVING(COUNT(?library) > 1)
