#Retrieve all library employees along with their contact points.

PREFIX ex: <http://example.org/library>
PREFIX schema: <http://schema.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dt: <http://example.org/dt#>
PREFIX cdesc: <http://example.org/cdesc#>

SELECT ?authorName
WHERE {
  	?author a dt:Author;
  			foaf:givenName ?authorName.
    ?book a schema:Book;
            schema:creator ?author.
    ?library a schema:Library;
            foaf:name ?libraryName;
            cdesc:hasInventory ?book.
}
GROUP BY ?authorName
HAVING(COUNT(?library) > 1)
